DATA_FOLDER = '/Users/rhythmicstar/ipython_notebook/nmd/00_data/'
NOTEBOOK_FOLDER = '/Users/rhythmicstar/ipython_notebook/nmd/01_notebooks/'
FIGURE_FOLDER = '/Users/rhythmicstar/ipython_notebook/nmd/02_figures/'
UPF1_FOLDER = '/Users/rhythmicstar/Desktop/tscc/UPF1/'
INPUT_FILES_FOLDER = '/Users/rhythmicstar/ipython_notebook/nmd/00_data/input_files'